[0;33m--- WARNING: GDB cannot open serial ports accessed as COMx[0m
[0;33m--- Using \\.\COM7 instead...[0m
[0;33m--- esp-idf-monitor 1.3.2 on \\.\COM7 115200 ---[0m
[0;33m--- Quit: Ctrl+] | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H ---[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x4008151c: call_start_cpu1 at C:/Users/Daniel/esp/esp-idf/components/esp_system/port/cpu_start.c:154
[0m
[0;33m0x40080400: _init at ??:?
[0m
[0;33m0x4008151c: call_start_cpu1 at C:/Users/Daniel/esp/esp-idf/components/esp_system/port/cpu_start.c:154
[0m
[0m
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Daniel\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\__main__.py", line 4, in <module>
    main()
  File "C:\Users\Daniel\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\idf_monitor.py", line 425, in main
    monitor.main_loop()
  File "C:\Users\Daniel\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\idf_monitor.py", line 178, in main_loop
    self._main_loop()
  File "C:\Users\Daniel\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\idf_monitor.py", line 294, in _main_loop
    super()._main_loop()
  File "C:\Users\Daniel\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\idf_monitor.py", line 226, in _main_loop
    self.serial_handler.handle_serial_input(data, self.console_parser, self.coredump,  # type: ignore
  File "C:\Users\Daniel\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\base\serial_handler.py", line 128, in handle_serial_input
    self.logger.handle_possible_pc_address_in_line(line_strip)
  File "C:\Users\Daniel\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\base\logger.py", line 157, in handle_possible_pc_address_in_line
    translation = lookup_pc_address(num, self.toolchain_prefix, self.elf_file)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Daniel\.espressif\python_env\idf5.1_py3.11_env\Lib\site-packages\esp_idf_monitor\base\output_helpers.py", line 36, in lookup_pc_address
    translation = subprocess.check_output(cmd, cwd='.')
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "subprocess.py", line 466, in check_output
  File "subprocess.py", line 571, in run
subprocess.CalledProcessError: Command '['xtensa-esp32-elf-addr2line', '-pfiaC', '-e', 'C:\\Users\\Daniel\\Desktop\\Bachelor_Arbeit\\Testing\\espnow\\build\\espnow_example.elf', '0x40080400']' returned non-zero exit status 1.
